name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag krishnadheeraj/webscrapper:latest
    
    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       registry: docker.io
       username: "**************"
       password: "*************"

    - name: Build and Push docker image
      uses: docker/build-push-action@v6
      with:
       context: .
       push: true
       tags: krishnadheeraj/webscrapper:latest

  
